### ISSUE TITLE
컨트랙트 배포 오류

### ISSUE THREAD

**Issue by sungwonkong** [sungwonkong/LearningClub2022_Contract#2]
![image](https://user-images.githubusercontent.com/19399226/164007798-7b5309ec-6b3c-402f-9773-73d87f947f4c.png)

사이즈 문제라고 하는데 디플로이 오류는 처음 봤네용...
이건 어떻게 해야할까요..

@Soohan-Park

**Comment by Soohan-Park** [comment]
음 해당 이슈는 배포하려는 솔리디티 파일의 크기가 24kB 이상인 경우에 발생하는 이슈입니다!  
상세한 내용은 해당 알림에 나와있는 [EIP-170](https://eips.ethereum.org/EIPS/eip-170)을 참고해보시면 좋을 것 같습니다ㅎㅎ

일단, 제가 지금 다시 한 번 클레이튼 바오밥 네트워크에 배포해보았을 땐, 별 무리 없이 정상적으로 배포가 되긴 합니다!!  
TxHash: [0xaec4836fe6f33915ad181421204909bcbb409ee118f53210025a4352e770a3db](https://baobab.scope.klaytn.com/tx/0xaec4836fe6f33915ad181421204909bcbb409ee118f53210025a4352e770a3db)

혹시 지금도 계속 배포가 안되신다면, 해결방안으로는 어제 화이트리스트 적용하면서 쭉 살펴보니 사용되지 않는 컨트랙트들이 좀 있더라구요!  
따라서, 해당 부분들을 제거해줘서 전체적인 파일 사이즈를 줄여준다면, 해결할 수 있지 않을까 싶습니다!

제가 오늘 중으로 불필요한 컨트랙트 제거해서 다시 풀리퀘 올려두겠습니다 :)
